import type { QuestionPair } from './types';

export const SEED_PAIRS: QuestionPair[] = [
  {
    id: 'sleep_phone',
    majorityQuestion: 'How many hours of sleep do you usually get on a weeknight?',
    imposterQuestion: 'How many hours a day do you spend on your phone?',
    difficulty: 'easy',
  },
  // Added new pairs from user list
  { id: 'lottery_parents_vs_friend', majorityQuestion: 'If you won the lottery, what % would you give to your parents?', imposterQuestion: 'If you won the lottery, what % would you lend to a friend but never expect back?' },
  { id: 'siblings_vs_secret_pets', majorityQuestion: 'How many siblings do you have?', imposterQuestion: 'How many pets do you actually own in secret?' },
  { id: 'fav_icecream_vs_pretend_flavor', majorityQuestion: 'What’s your favorite ice-cream flavor?', imposterQuestion: 'Which ice-cream flavor have you pretended to love just to fit in?' },
  { id: 'breakfast_vs_dinner', majorityQuestion: 'What did you have for breakfast today?', imposterQuestion: 'What did you have for dinner last night?' },
  { id: 'steak_vs_eggs', majorityQuestion: 'How do you like your steak cooked?', imposterQuestion: 'How do you like your eggs cooked?' },
  { id: 'fav_icecream_vs_spice', majorityQuestion: 'What’s your favorite ice cream flavor?', imposterQuestion: 'What’s your favorite spice?' },
  { id: 'craziest_country_vs_visited', majorityQuestion: 'What’s the craziest country you’d unironically love to visit?', imposterQuestion: 'What’s a country you’ve actually visited?' },
  { id: 'nye_vs_friday', majorityQuestion: 'Where were you on last New Year’s Eve?', imposterQuestion: 'Where were you last Friday night?' },
  { id: 'farthest_travel_vs_longest_stay', majorityQuestion: 'What’s the farthest you’ve traveled from home?', imposterQuestion: 'What’s the longest you’ve ever lived in one place?' },
  { id: 'fav_movie_vs_song', majorityQuestion: 'What’s your all-time favorite movie?', imposterQuestion: 'What’s your all-time favorite song?' },
  { id: 'celebrity_dinner_vs_overrated', majorityQuestion: 'Which celebrity would you love to have dinner with?', imposterQuestion: 'Which celebrity do you secretly think is overrated?' },
  { id: 'best_superhero_vs_villain', majorityQuestion: 'Who is the best superhero and why?', imposterQuestion: 'Who is the best supervillain and why?' },
  { id: 'superhero_name_vs_dc', majorityQuestion: 'Whats the coolest superhero name you can come up with', imposterQuestion: 'Who’s your favorite DC character?' },
  { id: 'last_tv_vs_last_book', majorityQuestion: 'What was the last TV show you binge-watched?', imposterQuestion: 'What was the last book you read from cover to cover?' },
  { id: 'historical_vs_fictional', majorityQuestion: 'Which historical figure do you admire the most?', imposterQuestion: 'Which fictional character do you relate to the most?' },
  { id: 'dinner_historical_vs_worst_hookup', majorityQuestion: 'If you could have dinner with any historical figure, who would it be?', imposterQuestion: 'Worst person you could imagine hooking up with your grandmother' },
  { id: 'million_vs_thousand', majorityQuestion: 'If you won $1,000,000, what would you do with it?', imposterQuestion: 'If you won $1,000 what would you do with it?' },
  { id: 'dream_job_vs_first_job', majorityQuestion: 'What is your dream job?', imposterQuestion: 'What was your first job' },
  { id: 'spend_money_vs_waste_time', majorityQuestion: 'What’s something you spend too much money on?', imposterQuestion: 'What’s something you waste too much time on?' },
  { id: 'cash_in_wallet_vs_battery', majorityQuestion: 'How much cash is in your wallet right now?', imposterQuestion: 'What’s your phone’s battery percentage right now?' },
  { id: 'first_kiss_age_vs_bike_age', majorityQuestion: 'At what age did you have your first kiss?', imposterQuestion: 'At what age did you learn to ride a bike?' },
  { id: 'num_exes_vs_siblings', majorityQuestion: 'How many exes have you had?', imposterQuestion: 'How many siblings do you have?' },
  { id: 'celebrity_crush_vs_best_friend', majorityQuestion: 'Who is your celebrity crush?', imposterQuestion: 'Who is your best friend?' },
  { id: 'best_gift_partner_vs_parents', majorityQuestion: 'What’s the best gift you’ve ever received from a partner?', imposterQuestion: 'What’s the best gift you’ve ever received from your parents?' },
  { id: 'last_relationship_end_vs_last_job', majorityQuestion: 'How did your last relationship end?', imposterQuestion: 'Why did you leave your last job?' },
  { id: 'notice_attraction_vs_interview', majorityQuestion: 'What do you notice first when you’re attracted to someone?', imposterQuestion: 'What do you notice first when interviewing someone for a job?' },
  { id: 'embarrassing_date_vs_school', majorityQuestion: 'What’s the most embarrassing thing that happened to you on a date?', imposterQuestion: 'What’s the most embarrassing thing that happened to you at school?' },
  { id: 'mispronounce_vs_misspell', majorityQuestion: 'What word do you always mispronounce?', imposterQuestion: 'What word do you always misspell?' },
  { id: 'last_meal_vs_fast_food', majorityQuestion: 'What would you want your last meal to be?', imposterQuestion: 'Favorite fast food menu item' },
  { id: 'one_wish_vs_animal', majorityQuestion: 'If a genie granted you one wish, what would it be?', imposterQuestion: 'If you could be any animal for a day, which would you choose?' },
  { id: 'one_song_vs_one_movie', majorityQuestion: 'If you could only listen to one song for the rest of your life, which would it be?', imposterQuestion: 'If you could only watch one movie for the rest of your life, which would it be?' },
  { id: 'reality_show_vs_movie_genre', majorityQuestion: 'If you were on a reality TV show, which one would you choose?', imposterQuestion: 'If you were to star in a movie, what genre would it be?' },
  { id: 'num_close_friends_vs_pick_number', majorityQuestion: 'How many close friends do you have', imposterQuestion: 'Pick a number between range 1-50' },
  { id: 'cook_skill_vs_sing_skill', majorityQuestion: 'On a scale of 1–10, how good are you at cooking?', imposterQuestion: 'On a scale of 1–10, how good are you at singing?' },
  { id: 'grad_year_vs_birth_year', majorityQuestion: 'What year did you graduate high school?', imposterQuestion: 'What year were you born?' },
  { id: 'sleep_last_night_vs_work_hours', majorityQuestion: 'How many hours of sleep did you get last night?', imposterQuestion: 'How many hours of work do you have in a normal day?' },
  { id: 'fav_youtube_vs_game', majorityQuestion: 'What’s your favorite YouTube channel?', imposterQuestion: 'What’s your favorite video game?' },
  { id: 'most_used_app_vs_website', majorityQuestion: 'Which app do you use the most on your phone?', imposterQuestion: 'Which website do you visit most often?' },
  { id: 'first_child_name_vs_first_pet', majorityQuestion: 'What would you name your first child?', imposterQuestion: 'What was the name of your first pet?' },
  { id: 'parents_dont_know_vs_boss_dont_know', majorityQuestion: 'What’s one thing your parents still don’t know you did?', imposterQuestion: 'What’s one thing your boss or teacher doesn’t know you did?' },
  { id: 'childhood_hero_vs_fav_villain', majorityQuestion: 'Who was your childhood hero?', imposterQuestion: 'Favorite villain' },
  { id: 'proud_of_vs_regret', majorityQuestion: 'What’s one thing you’re extremely proud of?', imposterQuestion: 'What’s one thing you deeply regret?' },
  { id: 'erase_memory_vs_relive_memory', majorityQuestion: 'If you could erase one memory, which would it be?', imposterQuestion: 'If you could relive one memory, which would it be?' },
  { id: 'fav_comedy_vs_erotic', majorityQuestion: 'What’s your favorite comedy movie?', imposterQuestion: 'What’s your favorite erotic movie or novel? [Non-PG]' },
  { id: 'fav_sleep_position_vs_sex', majorityQuestion: 'What’s your favorite sleeping position?', imposterQuestion: 'What’s your favorite sex position? [Non-PG]' },
  { id: 'countries_visited_vs_people_slept', majorityQuestion: 'How many countries have you visited?', imposterQuestion: 'How many people have you slept with? [Non-PG]' },
  { id: 'strangest_eaten_vs_worn', majorityQuestion: 'What’s the strangest thing you’ve ever eaten?', imposterQuestion: 'What’s the strangest thing you’ve ever worn?' },
  { id: 'found_100_vs_lost_100', majorityQuestion: 'What would you do if you found $100 on the street?', imposterQuestion: 'What would you do if you lost $100 on the street?' },
  { id: 'change_first_name_vs_hair_color', majorityQuestion: 'If you could change your first name, what would you choose?', imposterQuestion: 'If you could change your hair color right now, what would it be?' },
  { id: 'give_up_hobby_vs_pick_new', majorityQuestion: 'If you had to give up one hobby, which would it be?', imposterQuestion: 'If you had to pick up a new hobby, which would it be?' },
  { id: 'live_fiction_world_vs_move_country', majorityQuestion: 'If you could live in any fictional world, which would it be?', imposterQuestion: 'If you could move to any real country, which would it be?' },
  { id: 'value_quality_vs_deadly_sin', majorityQuestion: 'Which quality do you value most in others?', imposterQuestion: 'Which of the seven deadly sins do you commit most?' },
  { id: 'overrated_vs_terrifies', majorityQuestion: 'What’s something you think is overrated?', imposterQuestion: 'What’s something that terrifies you?' },
  { id: 'red_flag_relationship_vs_job_dealbreaker', majorityQuestion: 'What’s a red flag for you in a relationship?', imposterQuestion: 'What’s a deal-breaker for you in a job?' },
  { id: 'last_lie_vs_last_gift', majorityQuestion: 'What was the last lie you told?', imposterQuestion: 'What was the last gift you gave someone?' },
  { id: 'reality_show_win_vs_olympic_sport', majorityQuestion: 'What reality show do you think you could win?', imposterQuestion: 'What Olympic sport do you think you could compete in?' },
  { id: 'best_music_decade_vs_fashion', majorityQuestion: 'Which decade has the best music?', imposterQuestion: 'Which decade has the best fashion?' },
  { id: 'save_item_fire_vs_zombie_hide', majorityQuestion: 'What one item would you save first if your house caught fire?', imposterQuestion: 'Where would you hide if a zombie apocalypse started?' },
  { id: 'famous_for_vs_minor_superpower', majorityQuestion: 'If you could be famous for one thing, what would it be?', imposterQuestion: 'If you could have one minor superpower, what would it be?' },
  { id: 'one_day_left_vs_invisible', majorityQuestion: 'If you had one day left to live, what would you do?', imposterQuestion: 'If you woke up invisible for a day, what would you do?' },
  { id: 'talk_to_animal_vs_deceased', majorityQuestion: 'If you could talk to one animal, which would it be?', imposterQuestion: 'If you could talk to one deceased person, who would you choose?' },
  { id: 'bring_back_vs_erase_person', majorityQuestion: 'If you could bring one person back from the dead, who would it be?', imposterQuestion: 'If you could erase one person from history, who would it be?' },
  { id: 'be_one_age_vs_any_job', majorityQuestion: 'If you could be one age forever, what age would you choose?', imposterQuestion: 'If you could have any job in the world, which would it be?' },
  { id: 'lose_one_sense_vs_lose_leisure', majorityQuestion: 'If you had to lose one of your five senses, which?', imposterQuestion: 'If you had to give up one leisure activity forever, which?' },
  { id: 'cartoon_scared_vs_crush', majorityQuestion: 'Which cartoon character scared you as a kid?', imposterQuestion: 'Which cartoon character did you have a crush on as a kid?' },
  { id: 'fav_athlete_vs_actor', majorityQuestion: 'Who is your all-time favorite athlete?', imposterQuestion: 'Who is your all-time favorite actor?' },
  { id: 'pet_peeve_vs_weird_habit', majorityQuestion: 'What’s your biggest pet peeve?', imposterQuestion: 'What’s your weirdest habit?' },
  {
    id: 'first_vs_dream_car',
    majorityQuestion: 'What was the first car you ever owned?',
    imposterQuestion: 'What is your dream car?',
    difficulty: 'easy',
  },
  {
    id: 'breakfast_vs_lunch',
    majorityQuestion: 'What do you usually eat for breakfast on weekdays?',
    imposterQuestion: 'What do you usually eat for lunch on weekdays?',
    difficulty: 'easy',
  },
  {
    id: 'favorite_color_vs_room_color',
    majorityQuestion: 'What is your favorite color?',
    imposterQuestion: 'What color are the walls in your bedroom?',
    difficulty: 'medium',
  },
  {
    id: 'city_temp_vs_room_temp',
    majorityQuestion: "What's the typical daytime temperature where you live right now?",
    imposterQuestion: 'What temperature do you set your AC to at home?',
    difficulty: 'medium',
  },
  {
    id: 'last_movie_vs_favorite_actor',
    majorityQuestion: 'What was the last movie you watched?',
    imposterQuestion: 'Who is your favorite actor?',
    difficulty: 'medium',
  },
  {
    id: 'coffee_freq_vs_tea_freq',
    majorityQuestion: 'How many cups of coffee do you drink per day?',
    imposterQuestion: 'How many cups of tea do you drink per day?',
    difficulty: 'hard',
  },
  {
    id: 'pet_age_vs_you_age',
    majorityQuestion: 'How old is your pet?',
    imposterQuestion: 'How old are you?',
    difficulty: 'hard',
  },
  {
    id: 'work_start_vs_gym_start',
    majorityQuestion: 'What time do you usually start work or class?',
    imposterQuestion: 'What time do you usually start your workout?',
    difficulty: 'hard',
  },
];


